#%RAML 1.0
title: SCIM 2.0
description: SCIM 2.0 RAML SAMPLE doc. Tested with Okta
version: 1.0
baseUri: /scim/v2
securitySchemes:
  basic:
    description: 'This API supports Basic Authentication'
    type: Basic Authentication
securedBy: [basic]
types: !include scim_types.raml
/Users: !include scim_user.raml
/Groups: !include scim_group.raml
/ServiceProviderConfig:
  get:
    headers:
      Authorization:
        type: string
    responses:
      200:
        description: The request has succeeded.
        body:
          application/json:
            example: !include examples/sample_service_provider_config.json
/ResourceTypes:
  get:
    headers:
      Authorization:
        type: string
    responses:
      200:
        body:
          application/json:
            example: !include examples/sample_resource_types.json
/Schemas:
  get:
    headers:
      Authorization:
        type: string
    responses:
      200:
        body:
          application/json:
            example: !include examples/sample_schemas.json